### ISSUE TITLE
Hmm, cannot publish

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/condition-circle#6]
For some reason, cannot publish, even after updating tokens

```
npm ERR! code ENEEDAUTH
npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

**Comment by pmowrer** [comment]
Not sure what's going on with that, but let's get this back on `semantic-release` 11 to begin debugging. The update to 11 wasn't complete as `semantic-release` was still being run the old way (which won't work in 11). I'd be happy to help debug further if necessary.

**Comment by pmowrer** [comment]
ping @bahmutov

**Comment by bahmutov** [comment]
I manually (horror!) published version 1.6.0 but still have no idea why the publishing is broken... Will merge a pull request, maybe it would fix it.

**Comment by obartra** [comment]
I had the same issue since `condition-circle` switched to semantic release v11 (since that is on the `next` not the `latest`). Manually installing `semantic-release@11.0.2` fixed it for me (if you are willing you use the `next` tag instead)

**Comment by bahmutov** [comment]
Thanks @obartra this worked! https://circleci.com/gh/bahmutov/condition-circle/33
